--- #YAML:1.0
name:                RPM2-LocalInstalled
version:             1.4
abstract:            Perl extension that returns a list of locally installed RPMs
license:             ~
author:              
    - Oliver Falk <oliver@linux-kernel.at>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    RPM2:                          0
    Sort::Versions:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
